sudo: true
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7.3"
install: pip install tox-travis
env:
  - ENV=pep8
  - ENV=py3
  - ENV=func-travis
comment: |
  install dependencies in script phase saving time on simpler test environments
  sudo back to ourself to activate lxd group membership executable search path
script:
  - if [ $ENV = 'func-travis' ]; then
       sudo apt remove -y --purge lxd lxd-client;
       sudo snap install lxd;
       sudo snap install juju --classic;
       sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment';
       sudo lxd waitready;
       sudo lxd init --auto;
       sudo usermod -a -G lxd travis;
       sudo su travis -c 'juju bootstrap --debug --no-gui localhost';
    fi
  - tox -c tox.ini -e $ENV
  - if [ $ENV = 'func-travis' ]; then
    sudo su travis -c 'juju status -m $(juju models --format yaml|grep "^- name:.*zaza"|cut -f2 -d/)';
    fi
